In [22]:
import pandas as pd
import numpy as np

In [41]:
data  = pd.read_csv('../data/ner/Persian-NER-part3.txt',sep = '\t',names=['word','tag'])

In [12]:
data['lenn'] = data.id.apply(lambda x:len(str(x)))

In [42]:
data.head(20)

         word    tag
0         این      O
1   بیانیه‌ها      O
2         نقش      O
3        مهمی  B-DAT
4          در      O
5    اعتراضات      O
6      گسترده      O
7       مردمی      O
8          در      O
9     ماه‌های      O
10         پس      O
11         از      O
12   انتخابات      O
13  داشته‌است      O
14          .      O
15      سلمان      O
16       ذاکر      O
17          ،      O
18    نماینده      O
19     ارومیه  B-LOC

In [32]:
x = data.head(200)
x['group'] = np.nan

C:\Users\mcnak\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [59]:
def generate_sentence_group(df):
    df['group'] = np.nan
    i = 1
    for j in range(df.shape[0]):
        if df.iloc[j,0] == '.':
            df.iloc[j,2] = 'Sentence_' + str(i)
            i = i + 1
    df = df.fillna(method ='bfill')
    return df

In [66]:
data =  generate_sentence_group(data)

In [68]:
data

              word    tag            group
0              این      O       Sentence_1
1        بیانیه‌ها      O       Sentence_1
2              نقش      O       Sentence_1
3             مهمی  B-DAT       Sentence_1
4               در      O       Sentence_1
...            ...    ...              ...
2676411      اموات      O  Sentence_100168
2676412         را      O  Sentence_100168
2676413      سگدید      O  Sentence_100168
2676414   می‌کردند      O  Sentence_100168
2676415          .      O  Sentence_100168

[2676416 rows x 3 columns]